### ISSUE TITLE
golang 1.16版本上

### ISSUE THREAD

**Issue by trh812** [knownsec/ksubdomain#46]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x42ff756]

goroutine 18 [running]:
github.com/google/gopacket/pcap.(*Handle).compileBPFFilter(0x0, 0x4592a31, 0x13, 0x0, 0x3e8, 0x0, 0x4c02100)
	/Users/boyhack/goprograms/pkg/mod/github.com/google/gopacket@v1.1.18/pcap/pcap.go:420 +0x26
github.com/google/gopacket/pcap.(*Handle).SetBPFFilter(0x0, 0x4592a31, 0x13, 0x0, 0x0)
	/Users/boyhack/goprograms/pkg/mod/github.com/google/gopacket@v1.1.18/pcap/pcap.go:456 +0x60
ksubdomain/core.Recv(0xc00002a9f8, 0x4, 0xc0000adae0, 0xc0001401b0, 0xc0001100c0)
	/Users/boyhack/GolandProjects/ksubdomain/core/recv.go:27 +0xc3
created by ksubdomain/core.Start
	/Users/boyhack/GolandProjects/ksubdomain/core/start.go:37 +0x209

**Comment by xiaocaigouwu** [comment]
解决了么我也是这样
