### ISSUE TITLE
扫多个子域名时，api报错

### ISSUE THREAD

**Issue by shadow1ng** [knownsec/ksubdomain#47]
![image](https://user-images.githubusercontent.com/39651966/110723984-f175f980-824f-11eb-9f27-2c4afaffe777.png)

![image](https://user-images.githubusercontent.com/39651966/110723967-e9b65500-824f-11eb-8f4e-8ba3b0a6b51d.png)
.\ksubdomain.exe -dl .\1.txt -api
```
panic: runtime error: invalid memory address or nil pointer dereference
stack traceback:
        <string>:16: in function <<string>:14>
        [G]: in function 'request'
        <string>:15: in main chunk
        [G]: ?

goroutine 6 [running]:
ksubdomain/core.(*Script).Scan(0xc0002a3fc8, 0xc0000a34e9, 0x7, 0x0, 0x0, 0x12)
        Y:/GolandProjects/ksubdomain/core/script.go:235 +0x36a
ksubdomain/core.(*Source).Scan(0xc000244050, 0xc0000e6840, 0xc0000a34e9, 0x7)
        Y:/GolandProjects/ksubdomain/core/sources.go:43 +0xd1
created by ksubdomain/core.(*Source).Feed
        Y:/GolandProjects/ksubdomain/core/sources.go:58 +0xc7
```

**Comment by Eattttt** [comment]
他这个批量读取子域名的就是有问题

**Comment by saucer-man** [comment]
有同学解了吗？发个pr？
