### ISSUE TITLE
扫描报错

### ISSUE THREAD

**Issue by linuxdy** [knownsec/ksubdomain#55]
1.正常扫描报错

pip22 ./ksubdomain -dl yungongsi.txt -filter-wild -o result.txt -l 2 

 _  __   _____       _         _                       _
| |/ /  / ____|     | |       | |                     (_)
| ' /  | (___  _   _| |__   __| | ___  _ __ ___   __ _ _ _ __
|  <    \___ \| | | | '_ \ / _| |/ _ \| '_   _ \ / _  | | '_ \
| . \   ____) | |_| | |_) | (_| | (_) | | | | | | (_| | | | | |
|_|\_\ |_____/ \__,_|_.__/ \__,_|\___/|_| |_| |_|\__,_|_|_| |_|

[INFO] Current Version: 0.7
[INFO] libpcap version 1.9.1
............................................................................................
[INFO] Use Device: en0
[INFO] Use IP: 11.22.34.2
[INFO] Local Mac:
[INFO] GateWay Mac:
[INFO] 加载内置字典
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x42ff756]

goroutine 34 [running]:
github.com/google/gopacket/pcap.(*Handle).compileBPFFilter(0x0, 0x4592a31, 0x13, 0x0, 0x3e8, 0x0, 0x4c02100)
	/Users/boyhack/goprograms/pkg/mod/github.com/google/gopacket@v1.1.18/pcap/pcap.go:420 +0x26
github.com/google/gopacket/pcap.(*Handle).SetBPFFilter(0x0, 0x4592a31, 0x13, 0x0, 0x0)
	/Users/boyhack/goprograms/pkg/mod/github.com/google/gopacket@v1.1.18/pcap/pcap.go:456 +0x60
ksubdomain/core.Recv(0xc0000b4b27, 0x3, 0xc0000fe3c0, 0xc0002e01f0, 0xc0002900c0)
	/Users/boyhack/GolandProjects/ksubdomain/core/recv.go:27 +0xc3
created by ksubdomain/core.Start
	/Users/boyhack/GolandProjects/ksubdomain/core/start.go:37 +0x209

![image](https://user-images.githubusercontent.com/50064309/138405230-cbd59030-2215-4496-837a-c14636551e20.png)

**Comment by 1191569886** [comment]
我也报错了
